### ISSUE TITLE
lily of the Void not getting the effect of mimiced items

### ISSUE THREAD

**Issue by butterball223** [Provismet/Provi-Origins#5]
### Type of Error

Incorrect Behaviour

### Description

sugarcane dosent gain speedboost
armor seems to work correctly
fire resistance from flower isnt working as i still take double

milk dosent provide hunger?, im unsure if this is a bug or if this is to remove current mimicry
wood seems to work
and it dosent destroy the item as clicking onto the slot where it is will bring it back
you stay stuck to poison

### Mod Version

1.6.1

### Minecraft Version

1.20.2

### Mod Loader

Fabric

### Steps to Reproduce

```bash
flowers dont work and arent destroyed

pick up flower
use the ability
the gauge fills up but the effect dosent seem to work
```

**Comment by butterball223** [comment]
it could also be a issue with server side stuff so im unsure fully, as it could be an issue with 1.6 being the server version and me trying 1.6.1

i am sorry if these are working... but the milk dosent seem to work in signal player so it could be a few issues...

**Comment by butterball223** [comment]
ok so its the serverside issue, im sorry but it seems good so im sorry

**Comment by Provismet** [comment]
> sugarcane dosent gain speedboost
armor seems to work correctly
fire resistance from flower isnt working as i still take double

> and it dosent destroy the item as clicking onto the slot where it is will bring it back
you stay stuck to poison  

Your server appears to be lagging. Check your connection or the strength of the server host. In general (this is true for every Origins power) powers execute on both the client (you) and the server.  
Your issue is symptomatic of the server failing to keep up.


> milk dosent provide hunger?, im unsure if this is a bug or if this is to remove current mimicry

This is intentional. Mimicries are removed with the secondary key, not with milk.

**Comment by Provismet** [comment]
> ok so its the serverside issue, im sorry but it seems good so im sorry

Beat me by a second there.
