### ISSUE TITLE
Worlds wont load in

### ISSUE THREAD

**Issue by Winibo1** [Provismet/Provi-Origins#6]
### Type of Error

Incorrect Behaviour

### Mod List

I'm using the recommended mods

Origins-1.20.1-1.10.0
Pehkui-3.7.8+1.14.4-1.20.1
lambdynamiclights-2.3.1+1.20.1

and also
Essential-fabric_1-20-1

the fabric api version is 0.85.0

### Description

I'm using fabric 1.20.1 / 0.15.6 version

I get this error code whenever I try to play on a singleplayer world

Internal Exception: net.minecraft.class_151: Non [a-z0-9/._-] character in path location: minecraft:\u0000

I can't really figure out what could be the problem.

### Mod Version

1.4.0 / 1.4.1 / 1.5.0 / 1.5.1 / 1.5.2

### Minecraft Version

1.20.1

### Mod Loader

Fabric

### Steps to Reproduce

```bash
I simply tried to create a new singleplayer world with the mods above
and i got the error message
```

### Crash Log

```bash
Internal Exception: net.minecraft.class_151: Non [a-z0-9/._-] character in path location: minecraft:\u0000
```

**Comment by Provismet** [comment]
This issue can't be reproduced with the mods described. Neither the updated versions, nor the versions listed cause this error.

Specifically this error is caused by a mod introducing a block or item with an invalid ID. Usually caused by putting capital letters in the ID.  
Provi's Origins introduces 2 blocks and 10 items, all of which have valid IDs.

I recommend you double check your mod list and perhaps even your datapacks.

**Comment by Provismet** [comment]
Upon further inspection, your issue is happening because something is trying to create a resource with the ID: `minecraft:\u0000`. In ASCII, \u0000 would be the code for a NUL character.

Provi's Origins does not register anything to the minecraft namespace, only adding a small amount of datapack content, and therefore cannot be the cause. It's likely that your issue is being caused a corrupted file, another mod, a faulty launcher, or a faulty resourcepack/datapack.

This issue is not present in development environments or a live environment using the Modrinth launcher. So I'm going to make this as closed.

If your issue persists and you're 100% it's being caused by this mod, feel free to reopen this issue.

**Comment by Winibo1** [comment]
I checked it.

I even asked a friend of mine to try it. Same error code.

There aren't any datapack or resourcepacks

![1](https://github.com/Provismet/Provi-Origins/assets/157289680/0e111960-dc81-4e54-962b-4910896b1784)
![2](https://github.com/Provismet/Provi-Origins/assets/157289680/1b496a3d-b412-495a-be6e-f8f4e67c3f1b)
![3](https://github.com/Provismet/Provi-Origins/assets/157289680/a054ca29-214e-4bc3-8030-a78025fb0b10)
![4](https://github.com/Provismet/Provi-Origins/assets/157289680/15355564-9dae-44be-b718-4c16eb06bfbc)

**Comment by Provismet** [comment]
I tested on the vanilla launcher with the exact same mods as your mod folder, with a fresh installation of Fabric 0.15.6 and there is no error occurring for me.

I recommend one of the following:
- Redownload all the mods from an official source such as Modrinth or CurseForge. You may simply have a corrupted file.
- Try again with the debug log open (you'll find the option for this in the Minecraft Launcher settings). This might give you more information about your error.

**Comment by Provismet** [comment]
![image](https://github.com/Provismet/Provi-Origins/assets/17149901/a05096ff-eb9a-4e7d-bb1c-77ed1475003c)

This is my modlist, everything works. All were freshly downloaded from Modrinth. Notably your download of Origins is 9kb smaller than mine; where did you download your mods from?

**Comment by Winibo1** [comment]
I got it from CurseForge, a few months ago. But now I redownload everything from Modrinth, they all have the same file size.
Unfortunately the same issue occurred.

These are the errors I saw in the logs.
![5](https://github.com/Provismet/Provi-Origins/assets/157289680/66fea4f5-ed90-4c34-99d4-2e2dda76f9e6)
![6](https://github.com/Provismet/Provi-Origins/assets/157289680/044c767c-e284-4b0e-8744-a8a80aada538)
![7](https://github.com/Provismet/Provi-Origins/assets/157289680/76c013fd-2aa5-4a29-83f7-88636be2be10)
![8](https://github.com/Provismet/Provi-Origins/assets/157289680/883779ad-23b6-4d98-bcc0-f153bdc4fbc4)

**Comment by Provismet** [comment]
You can ignore unregistered powers, that error won't affect your game at all and only occurs when ExtraDE Origins Addon is missing.

Do not post logs as images, please paste them as text or upload the logs or crash log as a text file. The full logs will contain a stacktrace that let's me read precisely where the error is being caused.

**Comment by Winibo1** [comment]
[2024-1-21.txt](https://github.com/Provismet/Provi-Origins/files/14002208/2024-1-21.txt)

**Comment by Provismet** [comment]
The `error while receiving "proviorigins:alraune/summoned_pull"` has never occured in any live or testing environment, though it is not causing your issue.

From the log, I can gather that the error is occurring in Apoli. For your information, Origins is actually 3 mods:
- Origins
- Apoli (the power system)
- Calio (the ability to read powers from datapacks)

The error is being triggered when Apoli tries to read the power list from the server (yes singleplayer also has a server). It seems that the networking is causing issues, powers are missing or corrupted.  
The error about the alraune power says that a ' ' (space) is missing is simply incorrect. You can read the [internal datapack](https://github.com/Provismet/Provi-Origins/blob/1.5.2/src/main/resources/data/proviorigins/powers/alraune/summoned_pull.json#L20) file for this power yourself. The error is listing that line as being a zero, which it clearly isn't.

Additionally, if you create an identifier with no namespace, then the namespace becomes `minecraft`. I believe a null value is somehow getting into your power list, becoming encoded as a NUL character (\u0000), and getting passed into an identifier. This would explain both `minecraft:` and `minecraft:\u0000` which appear in your errors.

All this is to say that you are experiencing an issue with Apoli's ability to read the power list from the Fabric Networking API. An issue which has nothing to do with this mod.  
At most I can only recommend updating your Fabric API, but even then that's unlikely to be the cause given that your issue is not reproducible on other machines.

You have an issue with your computer, possibly due to an overly aggressive antivirus. I'm not sure why your friend would be experiencing the same issue, but I can assure you that **no one else has ever reported this issue**.

Searching on Google, the Fabric discord, or the Origins discords yields **no results** for `minecraft:\u0000`.
