### ISSUE TITLE
`proviorigins:emissive` Does not work with LambsDynamicLights

### ISSUE THREAD

**Issue by Lunatrixen** [Provismet/Provi-Origins#9]
### Type of Error

Incorrect Behaviour

### Description

I have a power which uses `proviorigins:emissive` and has a specific light level set, but lambsdynamiclights doesnt seem to pick up on this.
![image](https://github.com/Provismet/Provi-Origins/assets/91378087/88be2715-a99a-4d2e-b3ac-b7b0c8c963ef)
![image](https://github.com/Provismet/Provi-Origins/assets/91378087/f100fbe3-a57c-494d-be33-c3e64c55a4ed)

### Mod Version

1.5.2

### Minecraft Version

1.20.1

### Mod Loader

Fabric

### Steps to Reproduce

```bash
1. Create emissive power
2. see error
```

**Comment by Provismet** [comment]
Can you confirm what version of LambDynamicLights you're using? I will investigate this when I get a chance.

**Comment by Lunatrixen** [comment]
2.3.2

**Comment by Provismet** [comment]
I've looked into this a little further and the cause is because you're missing a parameter in your power.

The `light` field only determines the strength of the emissive lighting, not the dynamic lighting.  
You need to add a `dynamic_light` field if you want to have dynamic lighting. Check the [Splinter's glow](https://github.com/Provismet/Provi-Origins/blob/1.20.2/src/main/resources/data/proviorigins/powers/splinter/arcane_glow.json) for reference.

**Comment by Lunatrixen** [comment]
alright ill go see if that works

**Comment by Lunatrixen** [comment]
seems to of worked, Thanks!
![image](https://github.com/user-attachments/assets/86a839d7-3730-467a-95d3-1b895e9f8c96)
